---

log:
  level: debug
  file:

app:
  listen: 8080
  auth: "JWT_USER_SECRET_LOYS"

database:
  master:
    addr: nginx:81
    username: postgres
    password: postgres
    database: loys

  slave:
    addr: nginx:80
    username: repl_user
    password: repl_user
    database: loys
